apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: brigade-worker-read-secrets
subjects:
- kind: ServiceAccount
  name: brigade-worker
  namespace: brigade
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-reader
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: brigade-worker-read-certificates
subjects:
- kind: ServiceAccount
  name: brigade-worker
  namespace: brigade
roleRef:
  kind: ClusterRole
  name: cert-reader
  apiGroup: rbac.authorization.k8s.io
