apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: brigade-k8s-gateway-event-reader
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: brigade-k8s-gateway-event-reader-role-binding
subjects:
- kind: ServiceAccount
  name: brigade-k8s-gateway-brigade-k8s-gateway
  namespace: brigade
roleRef:
  kind: Role
  name: brigade-k8s-gateway-event-reader
  apiGroup: rbac.authorization.k8s.io
